# Generated by Django 2.2.4 on 2019-09-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_articlemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'verbose_name': '文章管理', 'verbose_name_plural': '文章管理'},
        ),
    ]
